name: Perform Infisical Authentication
author: "Infisical"
description: "Perform Infisical authentication and export the obtained access token as an environment variable or a file"
branding:
  icon: "lock"
  color: "yellow"
inputs:
  method:
    description: "The authentication method to use (`universal`, `oidc`, `aws-iam`)"
    required: true

  client-id:
    description: "Machine Identity client ID (required if method is `universal`)"
    required: false
  client-secret:
    description: "Machine Identity secret key (required if method is `universal`)"
    required: false
  identity-id:
    description: "Machine Identity ID (required if method is `oidc` or `aws-iam`)"
    required: false
  oidc-audience:
    description: "Custom aud claim for the signed Github ID token (configurable if method is `oidc`)"
    required: false
  domain:
    description: "Infisical URL (defaults to `https://app.infisical.com`)"
    required: false
    default: "https://app.infisical.com"
  output-credential:
    description: "Whether to set the obtained access token as a step output (access-token)."
    required: false
    default: "true"
  output-env-credential:
    description: "Whether to export the obtained access token as an environment variable (INFISICAL_TOKEN). If you set this to false, you probably want to use output-credential."
    required: false
    default: "false"
  extra-headers:
    description: "Extra headers to add to all requests sent to Infisical"
    required: false
    default: ""
outputs:
  access-token:
    description: "The obtained Infisical access token (only set when output-credential is true)"
runs:
  using: "node20"
  main: "dist/index.cjs"
